### ISSUE TITLE
Photo is allowed to drop below top constraint on 4" screens

### ISSUE THREAD

**Issue by dr2391** [Hipo/HIPImageCropper#1]
Works fine on 3.5" screen. Here is a screenshot: 
![photo jan 23 5 38 24 pm](https://f.cloud.github.com/assets/5532434/1990067/37b514ca-847f-11e3-98f9-a1c83d857962.png)

**Comment by jmhobbs** [comment]
I'm seeing this too, horizontally.

![Preview](http://dropit.velvetcache.org.s3.amazonaws.com/jmhobbs/OTlgmvUF/iOS+Simulator+Screen+Shot+Apr+29%2C+2015%2C+4.04.57+PM.png)

**Comment by taylanpince** [comment]
Sorry for missing this earlier, I will investigate.

**Comment by jmhobbs** [comment]
Thanks @taylanpince!

**Comment by taylanpince** [comment]
I just pushed a complete rewrite of the cropper. I apologize for the delay, I didn't realize the version we had up here was so old. New version has been on production in several of our apps for almost a year now, so it should be battle tested.

@jmhobbs I really appreciate your pull request. It was definitely a step in the right direction but the rewrite also fixes the issue (along with a lot of other things) so I am not merging it. Thanks again.

**Comment by jmhobbs** [comment]
Woo hoo!  Thanks for the rewrite, I don't mind at all, I'd much rather have the battle tested version :)

:+1:
