### ISSUE TITLE
Circular mask

### ISSUE THREAD

**Issue by andreaslindahl** [Hipo/HIPImageCropper#4]
Is it possible to set a border radius for the actual mask displayed? I would like it to be a circle instead of a square.

**Comment by taylanpince** [comment]
Hi Andreas, this is not supported at the moment and there are no plans to support it, at least for now. Based on your requirements, you could get away with not really supporting circular crop, but just displaying it to the user as a circular view (just place an oval mask on top of the crop view).

If you end up implementing something reusable though, please feel free to send a merge request!

**Comment by andreaslindahl** [comment]
Just to be clear - I don't want the cropped image to be circular. Just the mask displayed, similar to how Instagram shows a circular mask when cropping and scaling your profile image. It would be nice if you could specify the CGPath used for the mask in the updateOverlay method, for example via a property.

**Comment by taylanpince** [comment]
Got it, not a priority for us right now but if you implement this please do send a PR!
