### ISSUE TITLE
Resize croparea

### ISSUE THREAD

**Issue by mrugesh-scrumsoft** [Hipo/HIPImageCropper#5]
How can I resize the crop Area which is being passed while initializing object of HIPImageCropperView?

**Comment by taylanpince** [comment]
Hello, you can pass the crop area size during initialization with this method: `initWithFrame:cropAreaSize:position:`

**Comment by mrugesh-scrumsoft** [comment]
So, I need to init object of HIPImageCropperView everytime when I want to just resize cropArea??

**Comment by taylanpince** [comment]
Yes, that would be required now. We don't need such a feature, but feel free to send a PR if you implement it. Should be fairly simple but a refactor of the init method would be needed.
